#include <SI_EFM8BB2_Register_Enums.h>

SI_SBIT(MOSI, SFR_P1, 2);
SI_SBIT(NSS, SFR_P1, 3);
SI_SBIT(CLK, SFR_P1, 4);

extern void enter_DefaultMode_from_RESET(void)
{
	//backup SFRPAGE
	uint8_t SFRPAGE_save = SFRPAGE;
	
	SFRPAGE = 0x00;
	//disable watchdog
	WDTCN = 0xDE; //First key
	WDTCN = 0xAD; //Second key
	P0MDOUT = P0MDOUT_B0__OPEN_DRAIN | P0MDOUT_B1__PUSH_PULL | P0MDOUT_B2__OPEN_DRAIN
		 | P0MDOUT_B3__PUSH_PULL | P0MDOUT_B4__OPEN_DRAIN | P0MDOUT_B5__OPEN_DRAIN
		 | P0MDOUT_B6__OPEN_DRAIN | P0MDOUT_B7__OPEN_DRAIN;
	P1MDOUT = P1MDOUT_B2__PUSH_PULL | P1MDOUT_B3__PUSH_PULL | P1MDOUT_B4__PUSH_PULL;
	P1SKIP = P1SKIP_B2__SKIPPED | P1SKIP_B3__SKIPPED | P1SKIP_B2__SKIPPED;
	XBR2 = XBR2_XBARE__ENABLED;
	XBR0 = XBR0_URT0E__ENABLED;
	CKCON0 = CKCON0_SCA__SYSCLK_DIV_4 | CKCON0_T0M__SYSCLK | CKCON0_T2MH__SYSCLK
		 | CKCON0_T2ML__SYSCLK | CKCON0_T3MH__SYSCLK | CKCON0_T3ML__SYSCLK
		 | CKCON0_T1M__PRESCALE; // (24'500'000/8/4)/(256-176) ~= 9570

	TH1 = 0xB0; //176
	TMOD = TMOD_T1M__MODE2;
	TCON = TCON_TR1__BMASK; //timer 1 enable
	IE = IE_ES0__ENABLED;
	
	MOSI = 0;
	CLK = 0;
	NSS = 1;
	
	//restore SFRPAGE
	SFRPAGE = SFRPAGE_save;

}


